### ISSUE TITLE
Feature Request: For favorite connections add a button to swap the locations

### ISSUE THREAD

**Issue by snm247** [grote/Liberario#29]
When searching for a new connection there is a button for swapping start and destination. When selecting a connection from the favorites there is no such button. It would be great to have this button there, too.

**Comment by Echolon** [comment]
Hi,
I would like to reopen for 2.00 . I know there is a "Swap" possibility via menu, but it is still hidden. I often use this functionallity once I go back. Other users can maybe rate my suggestion.

How ever AWESOME NEW VERSION! :heart:

**Comment by grote** [comment]
I think it would be better to create a new ticket for this. But anyway, I am already thinking how to bring back some search options to be easier accessible without cluttering the UI.
