### ISSUE TITLE
Use a more meaningful logo

### ISSUE THREAD

**Issue by htgoebel** [grote/Liberario#31]
The current logo stands for "Liberario", but for the users, a logo meaning "public transport" would be much easier to understand. So please, change the logo.

You can find some usable patterns [searching opencliparts for "train"](https://openclipart.org/search/?query=train). Maybe [this on](https://openclipart.org/detail/166999/express-train-patch-by-davidblyons) (when thickening some lines), as it looks a bit like the (H) used in Germany and by Öffi.

**Comment by grote** [comment]
For the 1.0 release, I'd consider changing the logo. The current proposal looks like this:
![ic_launcher](https://cloud.githubusercontent.com/assets/244947/8272953/cd10e6b6-1858-11e5-82c5-9a16c5874ad7.png)
Feedback is welcome!

**Comment by htgoebel** [comment]
Nice idea. Some thoughts:
- Both the colour and the outer shape have changed. From a marketing perspective, I would recommend to keep at least the colour. I'd even keep the outer shape, if there are no "major" reasons to change this (e.g. design guides).
- This looks like a bus. I'd personally prefer some train, because I think tram and trains are the superior vehicles. But this may come from a western-European point of view, as in many countries public transport is done by buses.

**Comment by DJaeger** [comment]
How about bus AND train?
Diagonally or vertically splitted a bus on the left and a train on the right.

**Comment by grote** [comment]
> How about bus AND train?

I'm afraid this would clutter the logo too much. It should be simple and easy to recognize.

**Comment by DJaeger** [comment]
For me only a bus is also fine.
This was simply a recommentation to make everyone happy. ;-)
