### ISSUE TITLE
Delay is missing at destionation/end station

### ISSUE THREAD

**Issue by htgoebel** [grote/Liberario#40]
The delay seams to be not shown at the destination station, at least if the destination is the last station of the train.

For now this issue is a reminder only. I have to verify it as I only had a single case yet. I will add a screenshot. If anybody can verify this issue, please add information. Thanks.

**Comment by innir** [comment]
Hi,

I think this bug is present (again), see:

![screenshot_2016-01-06-12-35-06](https://cloud.githubusercontent.com/assets/5419701/12153394/ec9b62e2-b4b9-11e5-847b-5bd05622914a.png)

Selected network is "Deutsche Bahn", Transportr 1.0.1 from F-Droid.

**Comment by grote** [comment]
> I think this bug is present (again)

Are you sure the data does have the delay for the end station? Did you try the same search at bahn.de?

**Comment by innir** [comment]
No, I'm not sure, but I can confirm that it works if they are, see:
![transportr](https://cloud.githubusercontent.com/assets/5419701/12153766/05ed8476-b4bc-11e5-86ba-4b0694987b4f.png)
 and the corresponding bahn.de:
![bahn de](https://cloud.githubusercontent.com/assets/5419701/12153825/6676aae8-b4bc-11e5-9efe-a9da2b46776f.png)

So I guess there's nothing you can do about :(

**Comment by grote** [comment]
Well, looks like there's no bug. If you see this again, please check with the bahn website right away and maybe refresh the trip to make sure the data is not just missing in the API response.
