### ISSUE TITLE
Sort options for favorite connections  | sort by recency 

### ISSUE THREAD

**Issue by lightonflux** [grote/Liberario#43]
The list with the past connection searches (tab with star) is sorted by the number of searches.

I used Liberario on a trip these days and had to do a lot of searches. After a while the sorting for number of searches made the list very confusing. It would have helped a lot if there was an option to sort the searches by recency.

**Comment by lightonflux** [comment]
I think it would be helpful if there was a android notification bubble when you press the sorting button. The bubble should tell the user if the list is sorted by "number of searches" or recency of the search as it might not be obvious for some users.

**Comment by grote** [comment]
Please open a new issue for new features. This one is implemented and closed.
