### ISSUE TITLE
Connection list sorting issue

### ISSUE THREAD

**Issue by lightonflux** [grote/Liberario#52]
See image.

![pic](https://cloud.githubusercontent.com/assets/1377943/4343008/41beff0a-404d-11e4-892e-c106f8e60d33.png)

Connection query 2014-09-19 departure 23:00 "Bremen Hbf" -> "Worpswede, Insel" via the DB api.

Earlier connection for context.

**Comment by lightonflux** [comment]
Just updated to 0.6, will test again and update this issue in the next days.

**Comment by grote** [comment]
Please do, because this should be fixed now as of f3f17460b

**Comment by lightonflux** [comment]
In a week of testing the new version I never encountered the bug. It is definitely dead for good.
