### ISSUE TITLE
Crashes on opening settings

### ISSUE THREAD

**Issue by losuler** [grote/Liberario#553]
**Describe the bug**
Transportr crashes when clicking on `Settings` to open the settings menu.

**To Reproduce**
1. Slide open the left side menu.
2. Click on `Settings`.
3. Transportr immediately crashes.

**Expected behavior**
The settings menu to appear when clicking on `Settings`.

**Versions**
 - **Transportr Version:** 2.0.4 (F-Droid)
 - **Device:** Pixel 1
 - **Android Version:** 8.1.0

**Troubleshooting**
Clearing app cache and data does not fix the issue.

**Logcat**
```
12-11 15:32:58.255   868  6531 I ActivityManager: START u0 {cmp=de.grobox.liberario/de.grobox.transportr.settings.SettingsActivity} from uid 10204
12-11 15:32:58.309 30276 30276 E AndroidRuntime: Process: de.grobox.liberario, PID: 30276
12-11 15:32:58.309 30276 30276 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.grobox.liberario/de.grobox.transportr.settings.SettingsActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
12-11 15:32:58.311   868  4602 W ActivityManager:   Force finishing activity de.grobox.liberario/de.grobox.transportr.settings.SettingsActivity
12-11 15:32:58.316   868  4602 W ActivityManager:   Force finishing activity de.grobox.liberario/de.grobox.transportr.map.MapActivity
12-11 15:32:58.325   868   908 I ActivityManager: Showing crash dialog for package de.grobox.liberario u0
12-11 15:32:58.813   868   907 W ActivityManager: Activity pause timeout for ActivityRecord{91232ea u0 de.grobox.liberario/de.grobox.transportr.settings.SettingsActivity t11982 f}
```

**Comment by wonder75** [comment]
Yes, same here. Settings can't be opened in 2.0.4.
App crashes instantly.

**Comment by Krzmbrzl** [comment]
This bug also occurs on my Huawei P7 running Android 4.4 (I think - 4.x for sure) - Transportr v2.0.4

**Comment by grote** [comment]
The bug occurs everywhere and is an easy fix. Will happen with the next release. No need to post "me toos" anymore ;)

**Comment by grote** [comment]
@ialokim I am super short on time right now. AFAIK, this is the only release blocker. Do you want to look into it, so I can do a release when time permits?

**Comment by ialokim** [comment]
> Do you want to look into it

No problem, has been quite simple :+1:
