### ISSUE TITLE
Modul Europe>Germany>VGS (Saar) defekt

### ISSUE THREAD

**Issue by Ceeee** [grote/Liberario#562]
Jede Suchanfrage steigt mit einer Java-Fehlermeldung aus.

Die App ist stabil liefert aber keine Resultate, vermutlich scheitert die Query und der Fehler des Servers wird zurückgemeldet.

**Comment by Ceeee** [comment]
Mangels copy&paste hier als Screenshot:

**Comment by grote** [comment]
Wenn du dir den screenshot genau anguckst (runterscrollst?), ist da ein hinweis zum upstream projekt, wo auch schon ein ticket dazu existiert: https://github.com/schildbach/public-transport-enabler/issues/246

cc @ialokim

**Comment by Ceeee** [comment]
Die Anzeige ist statisch, man kann nicht scrollen und ich habe vorher leider nur die Liste der offenen Issues angeschaut. Sorry für die Dopplung.

**Comment by ialokim** [comment]
Fixed by #568 and should be in the next Transportr release.
