### ISSUE TITLE
Position ex-/import with the geo: intent

### ISSUE THREAD

**Issue by X4fyr** [grote/Liberario#58]
Is it possible to add an export function of the stations as a geo: intent?
[Look under Maps](http://developer.android.com/guide/components/intents-common.html)

I don't know if the providers provide postion-information, but if so, I would be great to export the postions to "Google Maps" or "Osmand" for further navigation.

But what I think will be easy to implement is the import funktion via the geo: intent, because the parsing of geo-locations and find nearby stations via gps is right now functioning.

**Comment by grote** [comment]
Yes, that's easily possible and already implemented for walk ways.

**Comment by grote** [comment]
This is closed for export. Import is a lot more tricky since the selected network might not cover the geo coordinate. So before that can be implemented, we need automatic selection of network based on coordinates. Feel free to open a new ticket for those.
