### ISSUE TITLE
0.6-beta1 crashes reliably

### ISSUE THREAD

**Issue by mkesper** [grote/Liberario#64]
Crashes reliably on start, please see log.
Samsung S3 android 4.1.2

**Comment by mkesper** [comment]
E/AndroidRuntime(18675): 	at de.grobox.liberario.Preferences.getNetworkId(Preferences.java:44)
E/AndroidRuntime(18675): 	at de.grobox.liberario.StationsFragment.onCreateView(StationsFragment.java:65)
I/ActivityManager( 2284): Process de.grobox.liberario (pid 18675) (adj 9) has died.
E/AndroidRuntime(19964): 	at de.grobox.liberario.Preferences.getNetworkId(Preferences.java:44)
E/AndroidRuntime(19964): 	at de.grobox.liberario.StationsFragment.onCreateView(StationsFragment.java:65)
I/ActivityManager( 2284): Process de.grobox.liberario (pid 19964) (adj 9) has died.
D/org.fdroid.fdroid.AppDetails(15924): Getting application details for de.grobox.liberario
.

**Comment by grote** [comment]
Thanks! This is already fixed in 8c9d7c20, but there's another nasty issue that blocks beta 2 at the moment.
