### ISSUE TITLE
Incorrect times when walking

### ISSUE THREAD

**Issue by clacke** [grote/Liberario#67]
When first or last leg of a route is a walk, it's not included in start time, arrival time and total time.

Example: Search a route in the Sweden network from Stora torget, Järfälla to Kista Grönlandsgången, Stockholm on a weekday morning. In the list of routes, 567+178 takes ~50 mins, walking+178 takes ~30 mins, 567+metro takes ~30 mins. If you look at the details and add them up, they're all actually ~50 mins.

**Comment by clacke** [comment]
Liberario 0.5.3 from F-Droid.

**Comment by grote** [comment]
Thanks for reporting! For some reason, I thought it was a good idea to not include the walking times from/to the stations into the times/duration. Changed my mind and the implementation now.
