### ISSUE TITLE
Option for change homeadress

### ISSUE THREAD

**Issue by DJaeger** [grote/Liberario#69]
There should be an option to change your homeadress as it could change or could wrongly saved.

**Comment by grote** [comment]
It used to be possible to change the home address by long clicking the home button. The only possibility for this now is the home button in the rightmost tab.
I guess it is time for a proper preferences activity. This is very easy, so volunteers welcome! :)

**Comment by DJaeger** [comment]
No one will search for it in that tab.
It should really be located elsewhere.
