### ISSUE TITLE
Show All Buttons for Transport Products

### ISSUE THREAD

**Issue by lightonflux** [grote/Liberario#72]
The problem with the horizontal list of buttons that toggle the means of transport is that it is not obvious that you can scroll it. Because android hides the scrollbar pretty quickly.

So it might be helpful to less experienced users to add a line break in the list, so you don't have to scroll to the hidden buttons. 

In the screenshot you see only 7 of 9 buttons without any indication that there are 2 more.

I don't know if a line break is the best option, as it might look a bit weird if the second row has only 1 or two buttons, but there definitely needs to be an indicator that there are more buttons the user can toggle.

![screenshot_2015-04-27-21-24-26](https://cloud.githubusercontent.com/assets/1377943/7355743/2261c500-ed24-11e4-9304-7a365efc76a9.png)

**Comment by grote** [comment]
There is a small indication for scrolling the product icons when you open the app. I don't really see another way to make them fit on all screens. I think we can forget about a line break. The only thing that maybe could be done is using a small animation every time you unfold the products that indicates the possibility to scroll.

But honestly, how often do you use the product icons at all and how often do you *need* to exclude cable cars and ferries from your trips?

**Comment by petebp** [comment]
I think a possible solution is splitting the icons into "pages", perhaps depending on the screen-width, which you can change with an arrow-button on the right and left side:
![1](https://cloud.githubusercontent.com/assets/9938649/7381479/00c6baa0-ee04-11e4-869c-a7f6cc95692d.png)
![2](https://cloud.githubusercontent.com/assets/9938649/7381480/00c987e4-ee04-11e4-8b37-189ef417baf2.png)
