### ISSUE TITLE
Autocomplete should display town namens of stops

### ISSUE THREAD

**Issue by petebp** [grote/Liberario#73]
When searching for a stop, liberario should display the town Name, perhaps behind the stop name, to differ multiple equal named stops in the same network, e.g. Bahnhofstr. or town hall, which regulary exists multiple times.

I attached two screenshots to illustrate t

![screenshot_2015-04-27-14-27-54](https://cloud.githubusercontent.com/assets/9938649/7369466/88fdcd98-edb2-11e4-813a-4e875589b9a7.png)
![screenshot_2015-04-27-14-28-15](https://cloud.githubusercontent.com/assets/9938649/7369467/931a5d8c-edb2-11e4-9d60-6d5faa457c4d.png).

**Comment by grote** [comment]
Thanks for your high quality bug report with examples and screenshots. That's very appreciated! :)
