### ISSUE TITLE
[bug] To many changes of trains with "DB"

### ISSUE THREAD

**Issue by dktzde** [grote/Liberario#80]
When I search a really long connection with some rail replacement service inside and I have a look to the intermediate stations it ends before the last station.
Example:
Date: 2.7.2015; Time: 8:20 am
From: Siegmund-Adam-Straße 2-9 (Eschlkam)
To: Aachen Hbf
First Connection Table ends in "Düren" at 17:38 - I cannot see when the train will be in Aachen

Thanks a lot for the nice Program

**Comment by grote** [comment]
Which version are you using? I can't reproduce this with 0.6.1 and always see Aachen as the last stop with a time as expected.

**Comment by dktzde** [comment]
Using 0.6.1 from F-Droid. I still get the same bug. See also screenshot. 
(In the overview I see Aachen as expected, but not in the detailed view)

![screenshot_2015-06-25-13-59-51 1](https://cloud.githubusercontent.com/assets/12322609/8353852/ba3fbe80-1b42-11e5-8ace-0fb1b5f1e499.png)

**Comment by grote** [comment]
Thanks for the screenshot, I could reproduce this now. It comes from Deutsche Bahn that delivers the data like that. For some reason the final station is Düren and not Aachen. You can use bahn.de and get the same result.

The only thing I can fix here is to show Düren also in the overview, but this is fixed already in the current development version.

**Comment by dktzde** [comment]
I understand now, that there is no bug in Liberario. The only thing you could show is "wrong data from provider". ;-) 

Thanks that you already fixed it.
