### ISSUE TITLE
Feature suggestion: see the quantity of the changes of trains

### ISSUE THREAD

**Issue by dktzde** [grote/Liberario#81]
would be nice for me, to see how many changes of trains the different connections has.
(at the moment I cannot see this while using "db" as an operator)

**Comment by grote** [comment]
Don't you see the little icons in the trip overview? The number of icons is the number of different connection. I had hoped this is rather obvious and better than writing a number explicitly.

**Comment by dktzde** [comment]
I see it (you mean "RE3554" and so on?). My problem is, I normally going a long ride and I cannot distinguish 9 from 11 symbols at the first view. So it would still be nice for me to have an number.

**Comment by grote** [comment]
I do see the use case for very long rides. However, I am not sure how to best put this in the current UI without cluttering it too much for all other people that usually go on shorter rides.

**Comment by dktzde** [comment]
For me it would be most useful to see it in the overview. Would a setting-switch be possible? Like I could change settings for "normal" overview and "long distance overview"?

**Comment by grote** [comment]
In the next version, the number of changes will be shown only for long trips.

**Comment by dktzde** [comment]
Many thanks!
