### ISSUE TITLE
App no longer work with VVS Germany

### ISSUE THREAD

**Issue by dasdirksche** [grote/Liberario#847]
App answers any request to VVS germany with schildbach error. Issue already opened there.

**Comment by ialokim** [comment]
as reference: https://github.com/schildbach/public-transport-enabler/issues/521

**Comment by MugguGubbl** [comment]
as a workaround you can use NVBW instead

**Comment by dasdirksche** [comment]
Thanks.

**Comment by dasdirksche** [comment]
Solved with last update. Thanks.
