### ISSUE TITLE
Timetable in lockscreen

### ISSUE THREAD

**Issue by amilopowers** [grote/Liberario#85]
Hi there

First I would like to thank you for your amazing app. I am using it although I work for SBB.

I would love to see the same lockscreen view as in Oeffi. You open the connection you are about to use and lock the screen. When you then hit the unlock button again you can see your connection without unlocking the display via PIN.

**Comment by grote** [comment]
Hi,

great that you like the app! :)

The feature you suggest is really interesting, but unfortunately I think that from Android 5 onwards, lockscreen widgets are no longer supported by Android. Could it be that you are using Android 4 at the moment?

**Comment by amilopowers** [comment]
Currently I am using 5.x but I will check if oeffi still does it.

Yes it worked like that when I still used. 4.x.

You'll hear back from me.

Regars,
Ulrich

**Comment by amilopowers** [comment]
It still works.

The screenshot is after I hit the power/lock button. When I tap "back" I have to enter my PIN to use the phone.

I am on Android 5.1.1 (cyangenmod 12.1 Nightly), Nexus 5

![screenshot_2015-09-08-15-49-22](https://cloud.githubusercontent.com/assets/9914682/9736464/96e3b42a-5641-11e5-9b2f-b73d95725e93.png)

**Comment by grote** [comment]
Could you please also send me a screenshot of the lockscreen where you can somehow open this?

**Comment by amilopowers** [comment]
I am sorry I am not shure what you mean. 

I do not open it in the lockscreen. I search for a connection, choose which one of the proposed ones I want and tap it. Then I have the overview similar to that in that screenshot. Then I lock the screen (power/lock button) and put it in my pocket. Before the the first connection station I would take my phone out and hit once the power/lock button. And that's what appears the on my screen.

**Comment by grote** [comment]
Thanks for clarifying. When you try the same thing with Liberario, what is the actual outcome compared to the expected one?

**Comment by TheLastProject** [comment]
It sounds to me like Oeffi just catches the lock screen event, keeping the screen unlocked until the activity the user is in at that moment is left.

**Comment by amilopowers** [comment]
@grote I just see my regular lockscreen... I tried it with the "getrennt anzeigen" view but it doesn't work either.

You might have to check oeffi yourself. http://oeffi.schildbach.de/download.html

**Comment by grote** [comment]
I'm sorry, but I don't use proprietary software. That's the reason I developed Liberario.

When I search for a connection with Liberario and then show it on a separate screen, then wait for my screen to get locked and unlock it afterwards, I am still seeing the connection as before the screen got locked. Isn't this exactly what you are trying to do? I'm sorry, but I think I still don't understand the issue here....

**Comment by amilopowers** [comment]
Oh I didn't know that your app actually can do that! Because I always lock the screen by hand. 

Is there a way you can enable the lock button to perform that action as well?

**Comment by grote** [comment]
So I read our conversation again and my impression is that the only difference between Liberario's behavior and what you are describing is that a PIN or pattern needs to be entered for unlocking with Liberario while you want to go directly from unlock to the Liberario screen without any security features. Is that correct?

**Comment by amilopowers** [comment]
No. I like the way it works in Liberario.

The only thing is that I don't want to wait for the display to lock itself.

**Comment by grote** [comment]
Ok, then please try to explain me what the difference is from locking it yourself vs. waiting for it to lock.

**Comment by amilopowers** [comment]
It is just a matter of convenience and habit. And sometimes it is annoying to wait for the lock. Imagine you look quickly on your phone when you are about to leave the train. In my case it is kind of impossible to wait because my phone locks itself when I shake it to much which apparently counts as a manual lock.

I guess it is a balance between use and time to develop/implement. I do totally understand if you say no. Unfortunately I can not write code yet so I can't help (besides drawing OSM).

**Comment by DJaeger** [comment]
@grote: Your impression is correct.
Apps like Öffi, Komoot and GMaps are showing in front of the keyguard.
So for fast lookup you only need to put on your screen and do not have to unlock.
But the phone is still locked and if you want to access anything else you have to unlock it before.

This should be able to do with the following flag:
https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SHOW_WHEN_LOCKED

**Comment by grote** [comment]
Thanks a lot @DJaeger for the hint. Without you I would have been lost here.

**Comment by grote** [comment]
Thanks also @amilopowers for proposing this useful feature that I didn't know was possible. It will be part of the upcoming major release of Liberario.

**Comment by amilopowers** [comment]
Thank you for implementing and your patience!
