### ISSUE TITLE
Android 5 DatePicker lacks weekday

### ISSUE THREAD

**Issue by TheLastProject** [grote/Liberario#88]
First off, I cannot be sure if this report is still relevant, as there have been a fair bit of commits since the latest stable released on F-Droid. If it is not, excuse me for this issue.

In Liberario 0.6.1, the DatePicker scrolls in typical Holo style. On Android 4, this is nice, as it shows you what weekday is selected (Monday/Tuesday/etc.). However, on Android 5, only the date itself (08 Oct 2015) is shown. As I orient myself on the weekday (I know it is Thursday today, so I need to plan the journey for Friday), this forces me to scroll down from my notification area every time I plan a trip to make sure I am entering the right date.

It would be good if Liberario could use a Material DatePicker, at least on Android 5, so that it would be obvious what weekday is chosen. Some example screenshots are shown on https://github.com/wdullaer/MaterialDateTimePicker#material-datetime-picker---select-a-timedate-in-style.

**Comment by grote** [comment]
This should be already fixed in the latest code which is yet to be released. If the next major version does not fix this issue for you, please reopen.
