### ISSUE TITLE
After deleting favorites the selection is not reseted

### ISSUE THREAD

**Issue by dktzde** [grote/Liberario#92]
Hi, when I delete a favorite in Liberario, after deleting, an other favorit is selected. This is not what I want, after deleting there should be nothing selected. 
See also screenshot - I deletet "Paderborn -> ac", afterwards the connection which was the next in the list is selected.

![delete_1](https://cloud.githubusercontent.com/assets/12322609/10539310/fb11a8b4-73fe-11e5-96ca-9d5acb91154d.jpg)
![delete_2](https://cloud.githubusercontent.com/assets/12322609/10539311/fb2f38a2-73fe-11e5-9fb8-950975562a31.jpg)

**Comment by grote** [comment]
I am sorry, but I can not reproduce this. Neither with current master, nor with the latest release.
